name: mlpipeline
channels:
    - conda-forge
    - defaults
    - anaconda

dependencies:
    - python=3.7
    - pip
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - statsmodels
    - lightgbm
    - xgboost
    - scikit-learn
    - jupyter
    - jupyter_contrib_nbextensions

